services:
  - type: web
    name: image-location-app
    runtime: python
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
